# Generated by Django 4.1.4 on 2022-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngantri", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
